AMAZON_ACCESS_KEY_ID='AKIAIRXV5QKMV54AINLA'
AMAZON_SECRET_ACCESS_KEY='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'

AmazonServices = {
  :ec2 => RightAws::Ec2.new(AMAZON_ACCESS_KEY_ID, AMAZON_SECRET_ACCESS_KEY),
  :s3 => RightAws::S3.new(AMAZON_ACCESS_KEY_ID, AMAZON_SECRET_ACCESS_KEY)
}